# Importing Libraries

In [2]:
import pandas as pd
import numpy as np

# Initialising the dataframe

In [3]:
file = pd.read_csv(r"C:\Users\helen\Downloads\sales_orders.csv")

file

,order_id,order_date,customer_id,region,product,category,quantity,unit_price,discount_pct,status
0,1181,2026-01-02,4,VIC,Backpack,Accessories,5,85.58,0.0,Shipped
1,1103,2026-01-03,39,QLD,Pen Pack,Stationery,7,11.17,10.0,Shipped
2,1100,2026-01-06,18,VIC,Headphones,Electronics,4,172.78,15.0,Delivered
3,1033,2026-01-06,34,QLD,Laptop,Electronics,6,1270.35,0.0,Delivered
4,1169,2026-01-06,26,NSW,Monitor,Electronics,7,414.96,0.0,Cancelled
...,...,...,...,...,...,...,...,...,...,...
195,1155,2026-09-19,40,NSW,Desk,Furniture,3,539.06,5.0,Cancelled
196,1125,2026-09-21,13,QLD,Pen Pack,Stationery,6,11.05,5.0,Delivered
197,1156,2026-09-25,21,NSW,Notebook,Stationery,5,5.67,0.0,Delivered
198,1147,2026-09-25,18,NaN,Laptop,Electronics,4,1353.27,15.0,Delivered
199,1065,2026-09-25,1,QLD,Desk,Furniture,6,503.56,5.0,Cancelled

# Learning more about the dataframe

In [4]:
# top 5 rows of the dataframe
file.head()

,order_id,order_date,customer_id,region,product,category,quantity,unit_price,discount_pct,status
0,1181,2026-01-02,4,VIC,Backpack,Accessories,5,85.58,0.0,Shipped
1,1103,2026-01-03,39,QLD,Pen Pack,Stationery,7,11.17,10.0,Shipped
2,1100,2026-01-06,18,VIC,Headphones,Electronics,4,172.78,15.0,Delivered
3,1033,2026-01-06,34,QLD,Laptop,Electronics,6,1270.35,0.0,Delivered
4,1169,2026-01-06,26,NSW,Monitor,Electronics,7,414.96,0.0,Cancelled

In [5]:
# shows the "shape" of the dataframe, returns a tuple of (rows, columns), excl. the header
file.shape

(200, 10)

In [6]:
# shows the data types of each column in the dataframe
file.dtypes

order_id          int64
order_date          str
customer_id       int64
region              str
product             str
category            str
quantity          int64
unit_price      float64
discount_pct    float64
status              str
dtype: object

In [7]:
# combination of df.shape and df.dtypes, but shows more info 
file.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      200 non-null    int64
 1   order_date    200 non-null    str
 2   customer_id   200 non-null    int64
 3   region        195 non-null    str
 4   product       200 non-null    str
 5   category      200 non-null    str
 6   quantity      200 non-null    int64
 7   unit_price    200 non-null    float64
 8   discount_pct  192 non-null    float64
 9   status        200 non-null    str
dtypes: float64(2), int64(3), str(5)
memory usage: 15.8 KB

In [8]:
# shows general aggregate data for the dataframe
file.describe()

          order_id  customer_id    quantity   unit_price  discount_pct
count   200.000000   200.000000  200.000000   200.000000    192.000000
mean   1100.500000    20.815000    4.045000   349.556800      5.182292
std      57.879185    12.208852    1.916072   414.138373      5.819546
min    1001.000000     1.000000    1.000000     5.410000      0.000000
25%    1050.750000    10.000000    2.750000    12.370000      0.000000
50%    1100.500000    21.000000    4.000000   191.020000      5.000000
75%    1150.250000    33.000000    6.000000   489.590000     10.000000
max    1200.000000    40.000000    7.000000  1527.500000     15.000000

# Changing a series data type

In [9]:
# changing a series to be in datetime, instead of a string
file["order_date"] = pd.to_datetime(file["order_date"])

# Pandas Classes: Series vs Dataframe

In [10]:
# this is a series
type(file["unit_price"])

pandas.Series

In [11]:
# adding an additional square bracket makes Python think it's a list
# whenever python receives a list, it will return a dataframe
type(file[["unit_price"]])

pandas.DataFrame

# Aggregrate functions for series

In [12]:
# mean
file["unit_price"].mean()

np.float64(349.5568)

In [13]:
# max
file["unit_price"].max()

np.float64(1527.5)

In [14]:
# min
file["unit_price"].min()

np.float64(5.41)

In [15]:
# value_counts - groups values and gives the count of each
file["region"].value_counts()

region
NSW    63
VIC    49
QLD    48
WA     20
SA     15
Name: count, dtype: int64

 # Index and values

In [16]:
# return the range index of a series
file["unit_price"].index

RangeIndex(start=0, stop=200, step=1)

In [17]:
# prints all values of a series in an array
file["unit_price"].values

array([  85.58,   11.17,  172.78, 1270.35,  414.96,  182.7 ,  570.4 ,
         10.96,   10.87,  406.71,  434.02,  315.14,  191.27,  357.  ,
         96.45,    5.84,  309.3 ,  556.75,    5.46,  174.47,  172.76,
          5.97,    5.92,  563.56,  361.4 ,  505.6 ,  358.86,  188.62,
         12.15,  336.95, 1357.45,  173.91,  571.75,  459.07, 1377.71,
       1495.54,    6.46,    6.11,  551.41,    5.9 ,   11.76,   12.67,
        465.45, 1306.34,  440.47,   89.37,  472.93,  308.79, 1328.9 ,
        359.56,    6.12,   11.97,  343.61,  364.17,   12.68,  188.37,
         12.95,   12.56,   82.21,  470.27,  561.87,    6.18,  166.03,
         11.13,  421.88,   85.36,   12.7 ,    5.89, 1291.25,   93.75,
        474.63, 1344.58,  513.59,  163.13,  521.32,  492.72,  501.84,
       1327.66,  494.89,   11.38, 1393.7 ,  327.6 ,    6.42,  309.47,
         94.91,   12.22,   90.26,    6.11,   12.51,  448.19,    6.11,
          6.16,   11.1 ,   95.53,   13.16,  568.17,  449.07,   10.95,
        564.17,  487.38,  421.95,   12.1 ,  508.81,  489.01,   11.89,
        194.24,    6.48,   81.88,  468.13,  452.66,   10.82,   11.42,
         11.48,   12.6 ,   97.36,  343.77,  327.25,    6.34,    6.02,
        491.33,   11.  ,  469.59,   12.72,    5.88,  510.43,  412.03,
       1342.98,    5.44,  482.65, 1434.13,    6.44,   81.03,  426.11,
        556.69,  318.59, 1419.38,   12.42,  494.52,   12.42,  162.64,
        364.03,  542.95,  197.48,   92.77,   13.15, 1290.6 ,   81.54,
        165.67, 1417.41,    5.75,    6.14,  167.86,    5.66,   11.91,
        468.47,  331.34, 1502.7 , 1527.5 , 1433.64, 1383.22,  179.89,
          6.21,    6.56,   85.95,  497.59,  467.84,  550.54,  173.61,
        501.11,  332.15,   93.81,  188.72,  191.61, 1357.01,    5.41,
        190.77,  369.27,    5.58, 1504.81,  482.37,  472.26,   90.15,
         12.63,  567.82,   82.53,  177.53,  195.08,    5.81,  185.51,
        515.26,   11.36,  511.33,  187.23,  320.08,    5.54,  539.06,
         11.05,    5.67, 1353.27,  503.56])

# Selecting specific series

In [18]:
# just like the previous example, double square brackets always return a dataframe
file[["order_id","product","quantity"]]

     order_id     product  quantity
0        1181    Backpack         5
1        1103    Pen Pack         7
2        1100  Headphones         4
3        1033      Laptop         6
4        1169     Monitor         7
..        ...         ...       ...
195      1155        Desk         3
196      1125    Pen Pack         6
197      1156    Notebook         5
198      1147      Laptop         4
199      1065        Desk         6

[200 rows x 3 columns]

# Filtering rows

In [19]:
# Breaking down the statement
# df[]
# [   (condition1) & (condition2)    ]
# each condition references the series as you would normally

file[(file["region"] == "NSW") & (file["quantity"] > 3)]

,order_id,order_date,customer_id,region,product,category,quantity,unit_price,discount_pct,status
4,1169,2026-01-06,26,NSW,Monitor,Electronics,7,414.96,0.0,Cancelled
27,1041,2026-02-07,39,NSW,Headphones,Electronics,5,188.62,10.0,Delivered
29,1129,2026-02-08,37,NSW,Office Chair,Furniture,4,336.95,0.0,Delivered
36,1062,2026-02-16,6,NSW,Notebook,Stationery,5,6.46,5.0,Delivered
41,1149,2026-02-18,21,NSW,Pen Pack,Stationery,5,12.67,10.0,Delivered
48,1127,2026-03-05,37,NSW,Laptop,Electronics,6,1328.90,15.0,Delivered
50,1184,2026-03-07,3,NSW,Notebook,Stationery,4,6.12,15.0,Shipped
55,1009,2026-03-13,38,NSW,Headphones,Electronics,6,188.37,0.0,Delivered
56,1092,2026-03-14,35,NSW,Pen Pack,Stationery,4,12.95,15.0,Delivered
57,1016,2026-03-15,28,NSW,Pen Pack,Stationery,6,12.56,0.0,Delivered
70,1039,2026-03-25,4,NSW,Monitor,Electronics,4,474.63,0.0,Delivered
72,1109,2026-03-27,11,NSW,Desk,Furniture,7,513.59,0.0,Delivered
79,1101,2026-04-09,5,NSW,Pen Pack,Stationery,4,11.38,0.0,Delivered
86,1048,2026-04-23,39,NSW,Backpack,Accessories,5,90.26,NaN,Delivered
87,1075,2026-04-23,26,NSW,Notebook,Stationery,4,6.11,10.0,Delivered
89,1154,2026-04-28,13,NSW,Monitor,Electronics,7,448.19,NaN,Delivered
90,1098,2026-04-29,15,NSW,Notebook,Stationery,6,6.11,0.0,Cancelled
97,1135,2026-05-05,24,NSW,Pen Pack,Stationery,5,10.95,15.0,Delivered
108,1144,2026-05-20,7,NSW,Desk,Furniture,6,468.13,0.0,Delivered
113,1089,2026-05-27,31,NSW,Pen Pack,Stationery,5,12.60,15.0,Delivered
125,1194,2026-06-11,40,NSW,Monitor,Electronics,5,412.03,0.0,Shipped
134,1116,2026-06-28,5,NSW,Office Chair,Furniture,4,318.59,15.0,Delivered
136,1037,2026-06-29,23,NSW,Pen Pack,Stationery,7,12.42,0.0,Cancelled
142,1023,2026-07-10,31,NSW,Headphones,Electronics,7,197.48,15.0,Delivered
148,1117,2026-07-17,36,NSW,Laptop,Electronics,7,1417.41,5.0,Delivered
159,1010,2026-07-30,1,NSW,Laptop,Electronics,4,1383.22,0.0,Cancelled
168,1188,2026-08-13,4,NSW,Desk,Furniture,5,501.11,0.0,Delivered
177,1162,2026-08-29,2,NSW,Notebook,Stationery,4,5.58,0.0,Cancelled
179,1164,2026-08-30,8,NSW,Desk,Furniture,4,482.37,5.0,Cancelled
182,1002,2026-09-03,32,NSW,Pen Pack,Stationery,6,12.63,10.0,Delivered
184,1064,2026-09-07,17,NSW,Backpack,Accessories,5,82.53,5.0,Delivered
186,1182,2026-09-10,34,NSW,Headphones,Electronics,7,195.08,0.0,Shipped
188,1119,2026-09-11,20,NSW,Headphones,Electronics,6,185.51,0.0,Delivered
192,1074,2026-09-16,19,NSW,Headphones,Electronics,4,187.23,10.0,Cancelled
193,1137,2026-09-18,19,NSW,Office Chair,Furniture,6,320.08,5.0,Delivered
197,1156,2026-09-25,21,NSW,Notebook,Stationery,5,5.67,0.0,Delivered

In [20]:
file[(file["status"] == "Delivered") & (file["category"] == "Electronics")]

,order_id,order_date,customer_id,region,product,category,quantity,unit_price,discount_pct,status
2,1100,2026-01-06,18,VIC,Headphones,Electronics,4,172.78,15.0,Delivered
3,1033,2026-01-06,34,QLD,Laptop,Electronics,6,1270.35,0.0,Delivered
5,1072,2026-01-07,33,NSW,Headphones,Electronics,2,182.70,5.0,Delivered
9,1197,2026-01-13,24,VIC,Monitor,Electronics,5,406.71,15.0,Delivered
19,1018,2026-01-27,5,QLD,Headphones,Electronics,4,174.47,5.0,Delivered
20,1058,2026-01-28,26,QLD,Headphones,Electronics,6,172.76,15.0,Delivered
27,1041,2026-02-07,39,NSW,Headphones,Electronics,5,188.62,10.0,Delivered
31,1157,2026-02-10,30,SA,Headphones,Electronics,1,173.91,0.0,Delivered
35,1150,2026-02-14,28,QLD,Laptop,Electronics,6,1495.54,10.0,Delivered
42,1053,2026-02-20,20,VIC,Monitor,Electronics,4,465.45,0.0,Delivered
48,1127,2026-03-05,37,NSW,Laptop,Electronics,6,1328.90,15.0,Delivered
55,1009,2026-03-13,38,NSW,Headphones,Electronics,6,188.37,0.0,Delivered
59,1199,2026-03-17,26,VIC,Monitor,Electronics,6,470.27,0.0,Delivered
62,1142,2026-03-20,3,NaN,Headphones,Electronics,3,166.03,10.0,Delivered
70,1039,2026-03-25,4,NSW,Monitor,Electronics,4,474.63,0.0,Delivered
71,1138,2026-03-27,5,VIC,Laptop,Electronics,3,1344.58,0.0,Delivered
73,1168,2026-03-27,10,SA,Headphones,Electronics,3,163.13,0.0,Delivered
80,1001,2026-04-09,40,QLD,Laptop,Electronics,6,1393.70,0.0,Delivered
89,1154,2026-04-28,13,NSW,Monitor,Electronics,7,448.19,NaN,Delivered
99,1077,2026-05-07,34,SA,Monitor,Electronics,5,487.38,0.0,Delivered
100,1167,2026-05-07,10,QLD,Monitor,Electronics,1,421.95,5.0,Delivered
105,1052,2026-05-14,37,NSW,Headphones,Electronics,3,194.24,0.0,Delivered
119,1088,2026-06-04,22,SA,Monitor,Electronics,7,491.33,0.0,Delivered
121,1066,2026-06-06,39,VIC,Monitor,Electronics,3,469.59,0.0,Delivered
126,1069,2026-06-15,8,NSW,Laptop,Electronics,3,1342.98,5.0,Delivered
137,1111,2026-06-29,40,QLD,Monitor,Electronics,5,494.52,0.0,Delivered
139,1083,2026-07-01,11,QLD,Headphones,Electronics,7,162.64,0.0,Delivered
142,1023,2026-07-10,31,NSW,Headphones,Electronics,7,197.48,15.0,Delivered
145,1036,2026-07-14,5,QLD,Laptop,Electronics,6,1290.60,5.0,Delivered
147,1118,2026-07-16,3,QLD,Headphones,Electronics,5,165.67,0.0,Delivered
148,1117,2026-07-17,36,NSW,Laptop,Electronics,7,1417.41,5.0,Delivered
151,1178,2026-07-21,21,QLD,Headphones,Electronics,2,167.86,0.0,Delivered
156,1007,2026-07-26,18,VIC,Laptop,Electronics,6,1502.70,0.0,Delivered
157,1120,2026-07-27,24,WA,Laptop,Electronics,4,1527.50,NaN,Delivered
158,1170,2026-07-28,23,VIC,Laptop,Electronics,7,1433.64,0.0,Delivered
165,1136,2026-08-07,7,NSW,Monitor,Electronics,1,467.84,10.0,Delivered
167,1102,2026-08-12,27,WA,Headphones,Electronics,4,173.61,0.0,Delivered
171,1097,2026-08-18,5,WA,Headphones,Electronics,6,188.72,0.0,Delivered
173,1196,2026-08-25,33,VIC,Laptop,Electronics,5,1357.01,0.0,Delivered
175,1189,2026-08-29,34,VIC,Headphones,Electronics,4,190.77,0.0,Delivered
178,1104,2026-08-30,35,NSW,Laptop,Electronics,2,1504.81,0.0,Delivered
188,1119,2026-09-11,20,NSW,Headphones,Electronics,6,185.51,0.0,Delivered
198,1147,2026-09-25,18,NaN,Laptop,Electronics,4,1353.27,15.0,Delivered

In [21]:
# series.isin() function similar to in() function in SQL
# there are 2 round brackets as the function only accepts 1 argument

# breaking down the 4th condition
# ( condition 4 )
#  series.isin((string1, string2))

file[(file["status"] == "Delivered") & (file["category"] == "Electronics") 
     & (file["region"].isin(("VIC", "QLD")))]

,order_id,order_date,customer_id,region,product,category,quantity,unit_price,discount_pct,status
2,1100,2026-01-06,18,VIC,Headphones,Electronics,4,172.78,15.0,Delivered
3,1033,2026-01-06,34,QLD,Laptop,Electronics,6,1270.35,0.0,Delivered
9,1197,2026-01-13,24,VIC,Monitor,Electronics,5,406.71,15.0,Delivered
19,1018,2026-01-27,5,QLD,Headphones,Electronics,4,174.47,5.0,Delivered
20,1058,2026-01-28,26,QLD,Headphones,Electronics,6,172.76,15.0,Delivered
35,1150,2026-02-14,28,QLD,Laptop,Electronics,6,1495.54,10.0,Delivered
42,1053,2026-02-20,20,VIC,Monitor,Electronics,4,465.45,0.0,Delivered
59,1199,2026-03-17,26,VIC,Monitor,Electronics,6,470.27,0.0,Delivered
71,1138,2026-03-27,5,VIC,Laptop,Electronics,3,1344.58,0.0,Delivered
80,1001,2026-04-09,40,QLD,Laptop,Electronics,6,1393.70,0.0,Delivered
100,1167,2026-05-07,10,QLD,Monitor,Electronics,1,421.95,5.0,Delivered
121,1066,2026-06-06,39,VIC,Monitor,Electronics,3,469.59,0.0,Delivered
137,1111,2026-06-29,40,QLD,Monitor,Electronics,5,494.52,0.0,Delivered
139,1083,2026-07-01,11,QLD,Headphones,Electronics,7,162.64,0.0,Delivered
145,1036,2026-07-14,5,QLD,Laptop,Electronics,6,1290.60,5.0,Delivered
147,1118,2026-07-16,3,QLD,Headphones,Electronics,5,165.67,0.0,Delivered
151,1178,2026-07-21,21,QLD,Headphones,Electronics,2,167.86,0.0,Delivered
156,1007,2026-07-26,18,VIC,Laptop,Electronics,6,1502.70,0.0,Delivered
158,1170,2026-07-28,23,VIC,Laptop,Electronics,7,1433.64,0.0,Delivered
173,1196,2026-08-25,33,VIC,Laptop,Electronics,5,1357.01,0.0,Delivered
175,1189,2026-08-29,34,VIC,Headphones,Electronics,4,190.77,0.0,Delivered

In [22]:
# filtering rows by row and column names

# breaking down the statement
# df.loc[     ]
# row_slice_start:row_slice_end, [columns]
file.loc[0:5, ["product", "status"]]

      product     status
0    Backpack    Shipped
1    Pen Pack    Shipped
2  Headphones  Delivered
3      Laptop  Delivered
4     Monitor  Cancelled
5  Headphones  Delivered

In [23]:
# filtering by index

# breaking down the statement
# df.iloc[     ]
# row_slice_start:row_slice_end, [columns as index numbers]

file.iloc[0:5, [4, 9]]

      product     status
0    Backpack    Shipped
1    Pen Pack    Shipped
2  Headphones  Delivered
3      Laptop  Delivered
4     Monitor  Cancelled

# Creating columns

In [24]:
# creating the column
file["total"] = file["quantity"] * file["unit_price"] * (1 - file["discount_pct"] / 100)

# checking the values
file["total"]

0       427.900
1        70.371
2       587.452
3      7622.100
4      2904.720
         ...
195    1536.321
196      62.985
197      28.350
198    4601.118
199    2870.292
Name: total, Length: 200, dtype: float64

In [25]:
# checking all columns and new column we created, to see if the calculation was accurate
# i manually calculated the first row in excel to see if it worked

file[["quantity", "unit_price", "discount_pct", "total"]]

     quantity  unit_price  discount_pct     total
0           5       85.58           0.0   427.900
1           7       11.17          10.0    70.371
2           4      172.78          15.0   587.452
3           6     1270.35           0.0  7622.100
4           7      414.96           0.0  2904.720
..        ...         ...           ...       ...
195         3      539.06           5.0  1536.321
196         6       11.05           5.0    62.985
197         5        5.67           0.0    28.350
198         4     1353.27          15.0  4601.118
199         6      503.56           5.0  2870.292

[200 rows x 4 columns]

In [26]:
# creating a new column by extracting the "month" from another column

file["order_month"] = file["order_date"].dt.month

# checking both columns to see that the month was extracted correctly
file[["order_month", "order_date"]]

     order_month order_date
0              1 2026-01-02
1              1 2026-01-03
2              1 2026-01-06
3              1 2026-01-06
4              1 2026-01-06
..           ...        ...
195            9 2026-09-19
196            9 2026-09-21
197            9 2026-09-25
198            9 2026-09-25
199            9 2026-09-25

[200 rows x 2 columns]

In [27]:

# creating a new column called "Size", where depending on the "Total column", will show values of Large or Small
file["size"] = np.where(file["total"] > 1000, "Large", "Small")

#checking the column
file["size"]

0      Small
1      Small
2      Small
3      Large
4      Large
       ...
195    Large
196    Small
197    Small
198    Large
199    Large
Name: size, Length: 200, dtype: str

# Addressing missing data

In [28]:
# give me a sum of all records that have values of NA
file.isna().sum()

order_id        0
order_date      0
customer_id     0
region          5
product         0
category        0
quantity        0
unit_price      0
discount_pct    8
status          0
total           8
order_month     0
size            0
dtype: int64

In [29]:
# for any NA values in the column "discount_pct", replace with 0, and apply to the original dataframe
file.fillna({"discount_pct": 0}, inplace= True)

,order_id,order_date,customer_id,region,product,category,quantity,unit_price,discount_pct,status,total,order_month,size
0,1181,2026-01-02,4,VIC,Backpack,Accessories,5,85.58,0.0,Shipped,427.900,1,Small
1,1103,2026-01-03,39,QLD,Pen Pack,Stationery,7,11.17,10.0,Shipped,70.371,1,Small
2,1100,2026-01-06,18,VIC,Headphones,Electronics,4,172.78,15.0,Delivered,587.452,1,Small
3,1033,2026-01-06,34,QLD,Laptop,Electronics,6,1270.35,0.0,Delivered,7622.100,1,Large
4,1169,2026-01-06,26,NSW,Monitor,Electronics,7,414.96,0.0,Cancelled,2904.720,1,Large
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1155,2026-09-19,40,NSW,Desk,Furniture,3,539.06,5.0,Cancelled,1536.321,9,Large
196,1125,2026-09-21,13,QLD,Pen Pack,Stationery,6,11.05,5.0,Delivered,62.985,9,Small
197,1156,2026-09-25,21,NSW,Notebook,Stationery,5,5.67,0.0,Delivered,28.350,9,Small
198,1147,2026-09-25,18,NaN,Laptop,Electronics,4,1353.27,15.0,Delivered,4601.118,9,Large
199,1065,2026-09-25,1,QLD,Desk,Furniture,6,503.56,5.0,Cancelled,2870.292,9,Large

In [30]:
# dropping rows that have na values in the "region" column

file.dropna(subset="region", inplace= True)

# checking how many rows where dropped
file

,order_id,order_date,customer_id,region,product,category,quantity,unit_price,discount_pct,status,total,order_month,size
0,1181,2026-01-02,4,VIC,Backpack,Accessories,5,85.58,0.0,Shipped,427.900,1,Small
1,1103,2026-01-03,39,QLD,Pen Pack,Stationery,7,11.17,10.0,Shipped,70.371,1,Small
2,1100,2026-01-06,18,VIC,Headphones,Electronics,4,172.78,15.0,Delivered,587.452,1,Small
3,1033,2026-01-06,34,QLD,Laptop,Electronics,6,1270.35,0.0,Delivered,7622.100,1,Large
4,1169,2026-01-06,26,NSW,Monitor,Electronics,7,414.96,0.0,Cancelled,2904.720,1,Large
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,1008,2026-09-19,6,QLD,Notebook,Stationery,4,5.54,5.0,Delivered,21.052,9,Small
195,1155,2026-09-19,40,NSW,Desk,Furniture,3,539.06,5.0,Cancelled,1536.321,9,Large
196,1125,2026-09-21,13,QLD,Pen Pack,Stationery,6,11.05,5.0,Delivered,62.985,9,Small
197,1156,2026-09-25,21,NSW,Notebook,Stationery,5,5.67,0.0,Delivered,28.350,9,Small
199,1065,2026-09-25,1,QLD,Desk,Furniture,6,503.56,5.0,Cancelled,2870.292,9,Large

# Grouping and Aggregating

In [31]:
# outputs a series
file.groupby("region")["total"].sum()

region
NSW    70663.2150
QLD    96763.0905
SA     15695.3320
VIC    72333.2100
WA     10052.4730
Name: total, dtype: float64

In [32]:
# outputs a dataframe, pandas adds a new index
file.groupby("region")["total"].sum().reset_index()

  region       total
0    NSW  70663.2150
1    QLD  96763.0905
2     SA  15695.3320
3    VIC  72333.2100
4     WA  10052.4730

In [33]:
# grouping the category column based on the averages of the quantity column
file.groupby("category")["quantity"].mean()

category
Accessories    4.529412
Electronics    4.530303
Furniture      3.660000
Stationery     3.774194
Name: quantity, dtype: float64

In [34]:
# two aggregations at once
file.groupby("product").agg(
    order_count = ("order_id", "count"),
    total_sales = ("total", "sum"),
)

              order_count  total_sales
product
Backpack               17    6096.2715
Desk                   31   56356.9080
Headphones             23   16674.4150
Laptop                 21  128511.2055
Monitor                22   36906.6595
Notebook               30     596.2985
Office Chair           19   18935.9555
Pen Pack               32    1429.6070

In [35]:
# grouping 2 columns together

file.groupby(["region", "status"])["total"].sum()

region  status
NSW     Cancelled    15490.0590
        Delivered    50138.0900
        Shipped       5035.0660
QLD     Cancelled    26103.8185
        Delivered    48634.6240
        Shipped      22024.6480
SA      Cancelled        5.9700
        Delivered    15199.4470
        Shipped        489.9150
VIC     Cancelled    12808.3245
        Delivered    54049.9155
        Shipped       5474.9700
WA      Cancelled       46.4800
        Delivered     6478.9340
        Shipped       3527.0590
Name: total, dtype: float64

In [36]:
# outputting a data frame
file.groupby(["region", "status"])["total"].sum().reset_index()

   region     status       total
0     NSW  Cancelled  15490.0590
1     NSW  Delivered  50138.0900
2     NSW    Shipped   5035.0660
3     QLD  Cancelled  26103.8185
4     QLD  Delivered  48634.6240
5     QLD    Shipped  22024.6480
6      SA  Cancelled      5.9700
7      SA  Delivered  15199.4470
8      SA    Shipped    489.9150
9     VIC  Cancelled  12808.3245
10    VIC  Delivered  54049.9155
11    VIC    Shipped   5474.9700
12     WA  Cancelled     46.4800
13     WA  Delivered   6478.9340
14     WA    Shipped   3527.0590

In [37]:
# pivoting the dataframe
file.groupby(["region", "status"])["total"].sum().unstack()

status   Cancelled   Delivered    Shipped
region
NSW     15490.0590  50138.0900   5035.066
QLD     26103.8185  48634.6240  22024.648
SA          5.9700  15199.4470    489.915
VIC     12808.3245  54049.9155   5474.970
WA         46.4800   6478.9340   3527.059

# Sorting and ranking

In [ ]:
# for the column "total", sort by descending and give me the first 10 results
file["total"].sort_values(ascending= False).head(10)

158    10035.4800
148     9425.7765
43      9144.3800
156     9016.2000
80      8362.2000
34      8266.2600
35      8075.9160
3       7622.1000
145     7356.4200
129     7170.6500
Name: total, dtype: float64

In [ ]:
# for each group of "customer_id", calculate the total sales of each group.
# give me the top 5 spenders
file.groupby(["customer_id"])["total"].sum().sort_values(ascending= False).head(5).reset_index()

   customer_id       total
0            5  17269.1730
1           34  17248.6515
2           40  14431.2710
3            1  14112.7290
4           36  13861.9635

In [ ]:
# creating a pivot table
# total should be the values
# horizontal columns should be categories
# vertical columns should be region
# aggregation of totals is a sum
file.pivot_table(values= ["total"], columns= "category", index= ["region"], aggfunc= "sum")

               total
category Accessories Electronics   Furniture Stationery
region
NSW        1036.4275  44263.6165  24583.4060   779.7650
QLD        1635.0870  79004.2955  15687.1565   436.5515
SA          489.9150   6539.5100   8482.5860   183.3210
VIC        2367.6320  48982.4300  20600.8530   382.2950
WA          567.2100   3302.4280   5938.8620   243.9730

In [ ]:
# creating a dict and creating a new data frame
lookup_dict = {"region" : ["NSW", "VIC", "QLD", "WA", "SA"],
             "state_name": ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia"],
             "manager": ["Priya Nair", "Tom Henderson", "Mei Zhang", "Jack O'Connell", "Sofia Rossi" ]
             }

lookup_df = pd.DataFrame(lookup_dict)

In [ ]:
# left join
file.merge(right= lookup_df, how= "left", on= "region")

,order_id,order_date,customer_id,region,product,category,quantity,unit_price,discount_pct,status,total,order_month,size,state_name,manager
0,1181,2026-01-02,4,VIC,Backpack,Accessories,5,85.58,0.0,Shipped,427.900,1,Small,Victoria,Tom Henderson
1,1103,2026-01-03,39,QLD,Pen Pack,Stationery,7,11.17,10.0,Shipped,70.371,1,Small,Queensland,Mei Zhang
2,1100,2026-01-06,18,VIC,Headphones,Electronics,4,172.78,15.0,Delivered,587.452,1,Small,Victoria,Tom Henderson
3,1033,2026-01-06,34,QLD,Laptop,Electronics,6,1270.35,0.0,Delivered,7622.100,1,Large,Queensland,Mei Zhang
4,1169,2026-01-06,26,NSW,Monitor,Electronics,7,414.96,0.0,Cancelled,2904.720,1,Large,New South Wales,Priya Nair
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,1008,2026-09-19,6,QLD,Notebook,Stationery,4,5.54,5.0,Delivered,21.052,9,Small,Queensland,Mei Zhang
191,1155,2026-09-19,40,NSW,Desk,Furniture,3,539.06,5.0,Cancelled,1536.321,9,Large,New South Wales,Priya Nair
192,1125,2026-09-21,13,QLD,Pen Pack,Stationery,6,11.05,5.0,Delivered,62.985,9,Small,Queensland,Mei Zhang
193,1156,2026-09-25,21,NSW,Notebook,Stationery,5,5.67,0.0,Delivered,28.350,9,Small,New South Wales,Priya Nair
194,1065,2026-09-25,1,QLD,Desk,Furniture,6,503.56,5.0,Cancelled,2870.292,9,Large,Queensland,Mei Zhang

# Export

In [ ]:
delivered = pd.DataFrame(file.sort_values(by="order_date"))

In [91]:
delivered = delivered[delivered["status"] == "Delivered"]
delivered

,order_id,order_date,customer_id,region,product,category,quantity,unit_price,discount_pct,status,total,order_month,size
2,1100,2026-01-06,18,VIC,Headphones,Electronics,4,172.78,15.0,Delivered,587.4520,1,Small
3,1033,2026-01-06,34,QLD,Laptop,Electronics,6,1270.35,0.0,Delivered,7622.1000,1,Large
5,1072,2026-01-07,33,NSW,Headphones,Electronics,2,182.70,5.0,Delivered,347.1300,1,Small
7,1128,2026-01-11,6,WA,Pen Pack,Stationery,5,10.96,5.0,Delivered,52.0600,1,Small
8,1050,2026-01-12,12,NSW,Pen Pack,Stationery,1,10.87,15.0,Delivered,9.2395,1,Small
...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,1140,2026-09-15,1,QLD,Desk,Furniture,4,511.33,0.0,Delivered,2045.3200,9,Large
193,1137,2026-09-18,19,NSW,Office Chair,Furniture,6,320.08,5.0,Delivered,1824.4560,9,Large
194,1008,2026-09-19,6,QLD,Notebook,Stationery,4,5.54,5.0,Delivered,21.0520,9,Small
196,1125,2026-09-21,13,QLD,Pen Pack,Stationery,6,11.05,5.0,Delivered,62.9850,9,Small
197,1156,2026-09-25,21,NSW,Notebook,Stationery,5,5.67,0.0,Delivered,28.3500,9,Small

In [94]:
delivered.to_csv(r"Learning Pandas Basics\delivered.csv")

OSError: Cannot save file into a non-existent directory: 'Learning Pandas Basics'